name: Automatic Attendance Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '50 1 * * 1,2'  # 每周一、周二的 UTC 时间 1:50 对应北京时间 9:50

jobs:
  attendance-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Automatic Attendance Script
      run: python AutomaticAttendance.py

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Attendance Update
